spring.application.name=jobhub-backend
spring.datasource.url=jdbc:mysql://localhost:3306/jobhub_db
spring.datasource.username=root
spring.datasource.password=shubham@54321
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=jobhub_super_secret_key_change_this
app.jwt.expiration=86400000

server.port=8080